app = "tweedirect"
primary_region = "ams"

[env]
  TWEEDIRECT_HOST = "tweedirect.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
